### ISSUE TITLE
Use fixed pacakge version for typescript-cs-poco dependency

### ISSUE THREAD

**Issue by LunicLynx** [Evertras/gulp-typescript-cs-poco#10]
The dependency is given as git path. This just broke our build. Until the main property was fixed 3 hours ago.

**Comment by ffMathy** [comment]
This is still in the pipeline once I have set up build configurations for everything that publishes the packages as new stuff is out.

"Latest" gives a lot of flexibility and makes it easier to publish new things.

It sucks that I broke everything for you, but it has happened *once*.

If you want to refer to a static version, I suggest you use the following instructions instead: http://stackoverflow.com/questions/16350673/depend-on-a-branch-or-tag-using-a-git-url-in-a-package-json

I can then maybe tag commits in the future.
