### ISSUE TITLE
Add option for Recursive Directory search

### ISSUE THREAD

**Issue by chrizy** [Evertras/gulp-typescript-cs-poco#3]
Hi, Great tool..! Is there any way to have an option so that the source directory can search sub directories. I have about 200 models organised into folders and would like to keep folder structure when converted to .ts
Thanks
Chris

**Comment by Evertras** [comment]
This should be handled by Gulp.  Use `Models/**/*.cs` as your source file path (or whatever base folder they're in), then the output should keep that folder structure.  Let me know if that works or if there's an issue in the plugin that prevents this.

**Comment by chrizy** [comment]
Works a treat.  Thanks..!

**Comment by Evertras** [comment]
No problem, glad it worked!
