### ISSUE TITLE
Extending Models client side Typescript

### ISSUE THREAD

**Issue by chrizy** [Evertras/gulp-typescript-cs-poco#4]
This might be a best practice question, but I’m having issues auto gen my models and being able to extend them within typescript. This tool does a perfect job of creating the interface for each model, but I then need to manually create the class for each model (I will have about 200 to create) ideally these will be auto generated, and then separately extend the class with the additional logic required such as, IsValid, etc This would be maintained in a separate file to the auto gen'd code.

Any guidance greatly appreciated.
Chris

**Comment by Evertras** [comment]
Hey there!  Why do you need to create a class for each of these interfaces?  The models this tool is geared to handle are POCOs that should generally not have any fancy functionality.

**Comment by chrizy** [comment]
Hi,
I'm using Angular2 but with any of the main front end libraries, typically you will need to extend the models with some logic like in the examples below,.
Worst case scenario for me is that I manually create a class for each Model and that will implement the interface provided by this tool. that will make sure the class definition is correct.
Best case scenario is that the main class is auto generated and then I only have to write/maintain the functions I need to extend the model.

I'm really trying to see how others are solving this...
Thanks
Chris

```
class Customer {
    firstName: string;
    lastName: string;

    fullname()
    {
        return this.firstName + ' ' + this.lastName;
    }
}
```

**Comment by Evertras** [comment]
I think I see what you mean.  Would this work for you?

```
class Customer implements ICustomer {
    fullname()
    {
        // this.firstName and this.lastName are from ICustomer
        return this.firstName + ' ' + this.lastName;
    }
}
```

Where `ICustomer` is generated from the plugin.  This way you're still only actually implementing your custom logic, you get strong typechecking from the interface so you'll know when any of your POCOs change, and you don't have an autogenerated boilerplate overwriting all your changes every time.

**Comment by chrizy** [comment]
Yes that kind of works, but what you end up with having to implement the interface basically including all the properties to satisfy the typescript complier.

So the final implementation is (downside is having to manually maintain the properties in the class)

```
class Customer implements ICustomer {
    firstName: string;
    lastName: string;

    fullname()
    {
        return this.firstName + ' ' + this.lastName;
    }
}
// Auto generated code below
export interface ICustomer {
    firstName: string;
    lastName: string;
}
```

Alternative below, but It think this will run into problem with complex models containing a lot of child objects types..

```
class Customer extends CustomerDTO {

    fullname()
    {
        return this.firstName + ' ' + this.lastName;
    }
}

// Auto generated code below
class CustomerDTO
{
    firstName: string;
    lastName: string;
}
```

**Comment by Evertras** [comment]
Ahhh, my apologies, I see the problem now!

I think in this case it would be better to do something like this:

```
class CustomCustomer {
  customerData: ICustomer;
  CustomCustomer(data: ICustomer) {
    this.customerData = data;
  }
  fullname()
  {
    return this.customerData.firstName + ' ' + this.customerData.lastName;
  }
}

// Auto generated as before
export interface ICustomer {
  firstName: string;
  lastName: string;
}
```

Naming could use some work, but hopefully the idea makes sense.

**Comment by chrizy** [comment]
Thanks for the comments. I think my only real solution is to hope typescript get partial type support. https://github.com/Microsoft/TypeScript/issues/563 

Until that happens I'm going to have to fudge it a bit.
Thanks
