### ISSUE TITLE
In readme.md, toLower should be toLowerCase

### ISSUE THREAD

**Issue by Granga** [Evertras/gulp-typescript-cs-poco#5]
I believe there is a typo in the tutorial since I'm getting this error:

```
return propName[0].toLower() + propName.substring(1);

TypeError: propName[0].toLower is not a function
```

To fix it, every toLower() call should be replaced with toLowerCase().

**Comment by Evertras** [comment]
You are entirely correct.  Fixing, sorry!

**Comment by Evertras** [comment]
Fixed.
