### ISSUE TITLE
Broken package

### ISSUE THREAD

**Issue by jakubfijalkowski** [Evertras/gulp-typescript-cs-poco#8]
Are you aware that the current NPM package is broken? The repository [ffMathy/typescript-cs-poco](https://github.com/ffMathy/typescript-cs-poco) that is being referenced by latest `package.json` does not exist or is inaccessible. The change was introduced in b994231f by @ffMathy .

**Comment by ffMathy** [comment]
Yes, we are aware. @Evertras is to move the ownership of his repository to me. It will get back online.

**Comment by jakubfijalkowski** [comment]
Great. Good to know. Thanks!

**Comment by ffMathy** [comment]
The package should be back online now.
